### ISSUE TITLE
prettierrc shouldn't set trailingComma to "all" 

### ISSUE THREAD

**Issue by mbathke** [sevenval/frontend-configs#2]
trailing commas on function signatures are not spec conform whereas the ie11 throws a syntax error when it finds that. this will work only if a babel pre-processor is used for building applications, which then in return removes the trailing commas. 

in my opinion it would make more sense to set this option to "es5" which sets the trailing comma only for objects and arrays but keeps the function signature clean.

**Comment by marvinhagemeister** [comment]
@mbathke You'd be surprised, but trailing commas for function arguments was actually included in ECMAScript 2017. The original proposal can be found [here](https://github.com/tc39/proposal-trailing-function-commas) and there is a good page dedicated to [trailing commas on mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Function_calls). The syntax will indeed break in browsers which do not support `ES 2017`.

When creating the prettier config we asked someone from every team in our department to give their opinion about the preferred comma style. The majority was in favour of `trailingComma: all` because of reduced diff noise when reviewing PRs or single commits. There we don't have any projects without a build step anymore.

The cool thing about prettier is that the formatting changes will be applied automatically without users having to think about it. In your case I'd simply decide in your team on the preferred formatting style and change the `.prettierrc` config accordingly.

If you feel like that this is not enough and you'd like to make it the default for every project we do, you'd need to get the buy in of the majority of developers at sevenval. We'd be happy to update the config when the majority vote changes.

**Comment by marvinhagemeister** [comment]
If this is still an issue feel free to ping me to reopen it.

**Comment by mbathke** [comment]
No, not for now. I just think this is an important information one have to consider when building frontend applications.
